using Microsoft.EntityFrameworkCore.Migrations;

namespace WebAPI.Migrations
{
    public partial class FirstSeed : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'Normal', 0)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'VIP', 1000)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'Couple', 5000)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'Deluxe', 100000)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'First Class', 100000)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'Sofa', 50000)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'Row Title', 0)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'Exit', 0)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'Aisle', 0)
                INSERT INTO [dbo].[SeatTypes] ([Name], [ExtraFee]) VALUES (N'Spacing', 0)");

            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[CinemaChains] ([Name], [CountryCode], [Logo], [NoOfMaxSeats]) VALUES (N'Galaxy Cinema', N'VN', N'https://cdn.moveek.com/media/cache/square/05d40eb5d3c66e32dc62b7a055422166ab3d53e9.png', 8)
                INSERT INTO [dbo].[CinemaChains] ([Name], [CountryCode], [Logo], [NoOfMaxSeats]) VALUES (N'Cinestar', N'VN', N'https://cinestar.com.vn/pictures/400x400.png', 8)");

            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'TP. Hồ Chí Minh')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hà Nội')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Đà Nẵng')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hải Phòng')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Cần Thơ')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'An Giang')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bà Rịa - Vũng Tàu')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bắc Giang')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bắc Kạn')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bạc Liêu')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bắc Ninh')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bến Tre')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bình Định')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bình Dương')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bình Phước')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Bình Thuận')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Cà Mau')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Cao Bằng')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Đắk Lắk')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Đắk Nông')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Điện Biên')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Đồng Nai')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Đồng Tháp')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Gia Lai')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hà Giang')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hà Nam')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hà Tĩnh')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hải Dương')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hậu Giang')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hòa Bình')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Hưng Yên')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Khánh Hòa')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Kiên Giang')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Kon Tum')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Lai Châu')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Lâm Đồng')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Lạng Sơn')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Lào Cai')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Long An')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Nam Định')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Nghệ An')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Ninh Bình')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Ninh Thuận')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Phú Thọ')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Quảng Bình')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Quảng Nam')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Quảng Ngãi')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Quảng Ninh')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Quảng Trị')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Sóc Trăng')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Sơn La')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Tây Ninh')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Thái Bình')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Thái Nguyên')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Thanh Hóa')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'TP. Huế')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Tiền Giang')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Trà Vinh')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Tuyên Quang')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Vĩnh Long')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Vĩnh Phúc')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Yên Bái')
                INSERT INTO [dbo].[Cities] ([Name]) VALUES (N'Phú Yên')");

            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[Cinemas] ([Name], [Description], [Address], [Location], [CinemaChainId], [CityId]) VALUES (N'Galaxy Quang Trung', N'Rạp Galaxy Quang Trung nằm ở CoopMart Quang Trung, được xây dựng với tiêu chuẩn Hollywood, có 7 phòng chiếu (1000 chỗ ngồi), chuẩn âm thanh Dolby 7.1. Galaxy Quang Trung là rạp chiếu phim đầu tiên của Galaxy Cinema tại Gò Vấp, nằm trên trục đường nhộn nhịp Quang Trung, chất lượng dịch vụ luôn được bảo đảm cùng với giá vé cạnh tranh nhất cho cư dân trong khu vực.', N'304A Quang Trung, P.11, Q. Gò Vấp, Tp. Hồ Chí Minh', N'10.835980;106.663020', 1, 1)
                INSERT INTO [dbo].[Cinemas] ([Name], [Description], [Address], [Location], [CinemaChainId], [CityId]) VALUES (N'Galaxy Nguyễn Du', N'Rạp Galaxy Nguyễn Du nằm ở đường Nguyễn Du, là rạp chiếu phim đầu tiên của Galaxy Cinema được xây dựng với tiêu chuẩn Hollywood, có 5 phòng chiếu (1000 chỗ ngồi), chuẩn âm thanh Dolby 7.1', N'116 Nguyễn Du, Q.1, Tp. Hồ Chí Minh', N'10.754640;106.650920', 1, 1)
                INSERT INTO [dbo].[Cinemas] ([Name], [Description], [Address], [Location], [CinemaChainId], [CityId]) VALUES (N'Galaxy Tràng Thi', N'Galaxy Tràng Thi là rạp chiếu phim thứ 2 tại Hà Nội của Galaxy Cinema, Galaxy Tràng Thi cam kết luôn mang đến chất lượng dịch vụ ổn định và giá vé tốt nhất', N'Nguyễn Kim Tràng Thi, 10B Tràng Thi, Hàng Trống, Hoàn Kiếm, Hà Nội', N'21.026710;105.849130', 1, 2)
                INSERT INTO [dbo].[Cinemas] ([Name], [Description], [Address], [Location], [CinemaChainId], [CityId]) VALUES (N'Cinestar Hai Bà Trưng', N'Rạp Cinestar Hai Bà Trưng nằm ở Hai Ba Trưng - gần với Nhà văn hóa Thanh Niên, được xây dựng với tiêu chuẩn rạp Hollywood, chuẩn âm thanh Dolby 7.1', N'135 Hai Bà Trưng, P. Bến Nghé, Q.1, Tp. Hồ Chí Minh', N'10.763800;106.687317', 2, 1)
                INSERT INTO [dbo].[Cinemas] ([Name], [Description], [Address], [Location], [CinemaChainId], [CityId]) VALUES (N'Cinestar Huế', N'Rạp Cinestar Hai Bà Trưng nằm ở Hai Ba Trưng - gần với Nhà văn hóa Thanh Niên, được xây dựng với tiêu chuẩn rạp Hollywood, chuẩn âm thanh Dolby 7.1', N'25 Hai Bà Trưng, P. Vĩnh Ninh, Tp. Huế', N'16.460790;107.589820', 2, 56)");

            //migrationBuilder.Sql(@"
            //    INSERT INTO [dbo].[Movies] ([Imdb_Id], [Title], [Plot], [Directors], [Actors], [ReleaseDate], [Runtime], [AgeRating], [Poster], [Trailer]) VALUES (577922, N'Tenet', N'None', N'Christopher Nolan', N'John David Washington, Robert Pattinson, Elizabeth Debicki', 8/22/2020, 150, N'PG-13', N'https://image.movieglu.com/293631/AUS_293631h0.jpg', N'https://trailer.movieglu.com/293631_high_V3.mp4')
            //    INSERT INTO [dbo].[Movies] ([Imdb_Id], [Title], [Plot], [Directors], [Actors], [ReleaseDate], [Runtime], [AgeRating], [Poster], [Trailer]) VALUES (340102, N'The New Mutants', N'None', N'Josh Boone', N'Blu Hunt, Maisie Williams, Anya Taylor-Joy, Charlie Heaton', 9/2/2020, 94, N'NC-16', N'https://image.movieglu.com/242618/242618h1.jpg', N'https://trailer.movieglu.com/242618_high_V2.mp4')
            //    INSERT INTO [dbo].[Movies] ([Imdb_Id], [Title], [Plot], [Directors], [Actors], [ReleaseDate], [Runtime], [AgeRating], [Poster], [Trailer]) VALUES (27205, N'Inception', N'None', N'Christopher Nolan', N'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Marion Cotillard, Ken Watanabe', 8/6/2010, 148, N'PG-13', N'https://image.movieglu.com/311508/311508h1.jpg', N'https://www.youtube.com/watch?v=YoHD9XEInc0')
            //    INSERT INTO [dbo].[Movies] ([Imdb_Id], [Title], [Plot], [Directors], [Actors], [ReleaseDate], [Runtime], [AgeRating], [Poster], [Trailer]) VALUES (464052, N'Wonder Woman 1984', N'None', N'Patty Jenkins', N'Gal Gadot, Chris Pine, Kristen Wiig, Pedro Pascal, Connie Nielsen', 10/2/2020, 148, N'NC-16', N'https://www.posters.eu/media/catalog/product/cache/cb3faf85ecb1e071fdba48f981c86454/g/b/gb_fp4879.jpg', N'https://www.youtube.com/watch?v=XW2E2Fnh52w')
            //    INSERT INTO [dbo].[Movies] ([Imdb_Id], [Title], [Plot], [Directors], [Actors], [ReleaseDate], [Runtime], [AgeRating], [Poster], [Trailer]) VALUES (496243, N'Parasite', N'None', N'Bong Joon-ho', N'Jang Young-hwan, Kwak Sin-ae, Moon Yang-kwon', 6/21/2019, 132, N'NC-18', N'https://images-na.ssl-images-amazon.com/images/I/91sustfojBL._AC_SY879_.jpg', N'https://www.youtube.com/watch?v=gQBtd75imHE')");

            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (57922, 1, 0)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (340102, 1, 0)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (27205, 1, 0)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (496243, 1, 0)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (464052, 1, 1)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (57922, 2, 0)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (340102, 2, 0)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (27205, 2, 0)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (496243, 2, 0)
                INSERT INTO [dbo].[MoviesInCinemaChains] ([MovieId], [CinemaChainId], [Status]) VALUES (464052, 2, 1) ");

            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 1', 10, 6, 1, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 2', 10, 6, 1, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 1', 10, 6, 2, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 2', 10, 6, 2, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 1', 10, 6, 3, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 2', 10, 6, 3, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 1', 10, 6, 4, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 2', 10, 6, 4, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 1', 10, 6, 5, NULL)
                INSERT INTO [dbo].[Rooms] ([Name], [Cols], [Rows], [CinemaId], [RoomTypeId]) VALUES (N'Cinema 2', 10, 6, 5, NULL)");

            //Seats của Cinema 1 & 2 của Galaxy Quang Trung
            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A', 0, 0, 2, 1, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 0, 1, 2, 1, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A1', 0, 2, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A2', 0, 3, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A3', 0, 4, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A4', 0, 5, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A5', 0, 6, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A6', 0, 7, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A7', 0, 8, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A8', 0, 9, 0, 1, NULL, 1)
               
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B', 1, 0, 2, 1, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 1, 1, 2, 1, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B1', 1, 2, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B2', 1, 3, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B3', 1, 4, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B4', 1, 5, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B5', 1, 6, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B6', 1, 7, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B7', 1, 8, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B8', 1, 9, 0, 1, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C', 2, 0, 2, 1, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 2, 1, 2, 1, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C1', 2, 2, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C2', 2, 3, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C3', 2, 4, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C4', 2, 5, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C5', 2, 6, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C6', 2, 7, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C7', 2, 8, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C8', 2, 9, 0, 1, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D', 3, 0, 2, 1, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 3, 1, 2, 1, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D1', 3, 2, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D2', 3, 3, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D3', 3, 4, 0, 1, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D4', 3, 5, 0, 1, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D5', 3, 6, 0, 1, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D6', 3, 7, 0, 1, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D7', 3, 8, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D8', 3, 9, 0, 1, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E', 4, 0, 2, 1, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 4, 1, 2, 1, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E1', 4, 2, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E2', 4, 3, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E3', 4, 4, 0, 1, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E4', 4, 5, 0, 1, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E5', 4, 6, 0, 1, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E6', 4, 7, 0, 1, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E7', 4, 8, 0, 1, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E8', 4, 9, 0, 1, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F', 5, 0, 2, 1, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 1, 2, 1, NULL, 8)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 2, 2, 1, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 3, 2, 1, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F3', 5, 4, 0, 1, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F4', 5, 5, 0, 1, 55, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F5', 5, 6, 0, 1, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F6', 5, 7, 0, 1, 57, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 8, 2, 1, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 9, 2, 1, NULL, 10)
                
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A', 0, 0, 2, 2, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 0, 1, 2, 2, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A1', 0, 2, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A2', 0, 3, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A3', 0, 4, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A4', 0, 5, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A5', 0, 6, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A6', 0, 7, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A7', 0, 8, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A8', 0, 9, 0, 2, NULL, 1)
               
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B', 1, 0, 2, 2, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 1, 1, 2, 2, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B1', 1, 2, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B2', 1, 3, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B3', 1, 4, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B4', 1, 5, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B5', 1, 6, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B6', 1, 7, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B7', 1, 8, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B8', 1, 9, 0, 2, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C', 2, 0, 2, 2, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 2, 1, 2, 2, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C1', 2, 2, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C2', 2, 3, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C3', 2, 4, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C4', 2, 5, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C5', 2, 6, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C6', 2, 7, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C7', 2, 8, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C8', 2, 9, 0, 2, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D', 3, 0, 2, 2, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 3, 1, 2, 2, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D1', 3, 2, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D2', 3, 3, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D3', 3, 4, 0, 2, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D4', 3, 5, 0, 2, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D5', 3, 6, 0, 2, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D6', 3, 7, 0, 2, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D7', 3, 8, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D8', 3, 9, 0, 2, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E', 4, 0, 2, 2, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 4, 1, 2, 2, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E1', 4, 2, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E2', 4, 3, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E3', 4, 4, 0, 2, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E4', 4, 5, 0, 2, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E5', 4, 6, 0, 2, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E6', 4, 7, 0, 2, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E7', 4, 8, 0, 2, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E8', 4, 9, 0, 2, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F', 5, 0, 2, 2, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 1, 2, 2, NULL, 8)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 2, 2, 2, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 3, 2, 2, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F3', 5, 4, 0, 2, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F4', 5, 5, 0, 2, 115, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F5', 5, 6, 0, 2, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F6', 5, 7, 0, 2, 117, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 8, 2, 2, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 9, 2, 2, NULL, 10)");

            //Seats của Cinema 1 & 2 của Galaxy Nguyễn Du
            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A', 0, 0, 2, 3, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 0, 1, 2, 3, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A1', 0, 2, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A2', 0, 3, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A3', 0, 4, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A4', 0, 5, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A5', 0, 6, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A6', 0, 7, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A7', 0, 8, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A8', 0, 9, 0, 3, NULL, 1)

                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B', 1, 0, 2, 3, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 1, 1, 2, 3, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B1', 1, 2, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B2', 1, 3, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B3', 1, 4, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B4', 1, 5, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B5', 1, 6, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B6', 1, 7, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B7', 1, 8, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B8', 1, 9, 0, 3, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C', 2, 0, 2, 3, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 2, 1, 2, 3, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C1', 2, 2, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C2', 2, 3, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C3', 2, 4, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C4', 2, 5, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C5', 2, 6, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C6', 2, 7, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C7', 2, 8, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C8', 2, 9, 0, 3, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D', 3, 0, 2, 3, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 3, 1, 2, 3, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D1', 3, 2, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D2', 3, 3, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D3', 3, 4, 0, 3, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D4', 3, 5, 0, 3, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D5', 3, 6, 0, 3, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D6', 3, 7, 0, 3, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D7', 3, 8, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D8', 3, 9, 0, 3, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E', 4, 0, 2, 3, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 4, 1, 2, 3, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E1', 4, 2, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E2', 4, 3, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E3', 4, 4, 0, 3, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E4', 4, 5, 0, 3, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E5', 4, 6, 0, 3, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E6', 4, 7, 0, 3, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E7', 4, 8, 0, 3, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E8', 4, 9, 0, 3, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F', 5, 0, 2, 3, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 1, 2, 3, NULL, 8)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 2, 2, 3, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 3, 2, 3, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F3', 5, 4, 0, 3, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F4', 5, 5, 0, 3, 175, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F5', 5, 6, 0, 3, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F6', 5, 7, 0, 3, 177, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 8, 2, 3, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 9, 2, 3, NULL, 10)
                
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A', 0, 0, 2, 4, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 0, 1, 2, 4, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A1', 0, 2, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A2', 0, 3, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A3', 0, 4, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A4', 0, 5, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A5', 0, 6, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A6', 0, 7, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A7', 0, 8, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A8', 0, 9, 0, 4, NULL, 1)
               
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B', 1, 0, 2, 4, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 1, 1, 2, 4, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B1', 1, 2, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B2', 1, 3, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B3', 1, 4, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B4', 1, 5, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B5', 1, 6, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B6', 1, 7, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B7', 1, 8, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B8', 1, 9, 0, 4, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C', 2, 0, 2, 4, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 2, 1, 2, 4, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C1', 2, 2, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C2', 2, 3, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C3', 2, 4, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C4', 2, 5, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C5', 2, 6, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C6', 2, 7, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C7', 2, 8, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C8', 2, 9, 0, 4, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D', 3, 0, 2, 4, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 3, 1, 2, 4, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D1', 3, 2, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D2', 3, 3, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D3', 3, 4, 0, 4, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D4', 3, 5, 0, 4, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D5', 3, 6, 0, 4, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D6', 3, 7, 0, 4, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D7', 3, 8, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D8', 3, 9, 0, 4, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E', 4, 0, 2, 4, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 4, 1, 2, 4, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E1', 4, 2, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E2', 4, 3, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E3', 4, 4, 0, 4, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E4', 4, 5, 0, 4, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E5', 4, 6, 0, 4, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E6', 4, 7, 0, 4, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E7', 4, 8, 0, 4, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E8', 4, 9, 0, 4, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F', 5, 0, 2, 4, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 1, 2, 4, NULL, 8)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 2, 2, 4, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 3, 2, 4, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F3', 5, 4, 0, 4, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F4', 5, 5, 0, 4, 235, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F5', 5, 6, 0, 4, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F6', 5, 7, 0, 4, 237, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 8, 2, 4, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 9, 2, 4, NULL, 10)");

            //Seats của Cinema 1 & 2 của Cinestar Hai Bà Trưng
            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A', 0, 0, 2, 7, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 0, 1, 2, 7, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A1', 0, 2, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A2', 0, 3, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A3', 0, 4, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A4', 0, 5, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A5', 0, 6, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A6', 0, 7, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A7', 0, 8, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A8', 0, 9, 0, 7, NULL, 1)

                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B', 1, 0, 2, 7, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 1, 1, 2, 7, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B1', 1, 2, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B2', 1, 3, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B3', 1, 4, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B4', 1, 5, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B5', 1, 6, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B6', 1, 7, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B7', 1, 8, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B8', 1, 9, 0, 7, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C', 2, 0, 2, 7, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 2, 1, 2, 7, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C1', 2, 2, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C2', 2, 3, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C3', 2, 4, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C4', 2, 5, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C5', 2, 6, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C6', 2, 7, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C7', 2, 8, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C8', 2, 9, 0, 7, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D', 3, 0, 2, 7, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 3, 1, 2, 7, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D1', 3, 2, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D2', 3, 3, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D3', 3, 4, 0, 7, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D4', 3, 5, 0, 7, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D5', 3, 6, 0, 7, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D6', 3, 7, 0, 7, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D7', 3, 8, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D8', 3, 9, 0, 7, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E', 4, 0, 2, 7, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 4, 1, 2, 7, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E1', 4, 2, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E2', 4, 3, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E3', 4, 4, 0, 7, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E4', 4, 5, 0, 7, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E5', 4, 6, 0, 7, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E6', 4, 7, 0, 7, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E7', 4, 8, 0, 7, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E8', 4, 9, 0, 7, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F', 5, 0, 2, 7, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 1, 2, 7, NULL, 8)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 2, 2, 7, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 3, 2, 7, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F3', 5, 4, 0, 7, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F4', 5, 5, 0, 7, 295, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F5', 5, 6, 0, 7, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F6', 5, 7, 0, 7, 297, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 8, 2, 7, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 9, 2, 7, NULL, 10)
                
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A', 0, 0, 2, 8, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 0, 1, 2, 8, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A1', 0, 2, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A2', 0, 3, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A3', 0, 4, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A4', 0, 5, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A5', 0, 6, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A6', 0, 7, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A7', 0, 8, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'A8', 0, 9, 0, 8, NULL, 1)
               
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B', 1, 0, 2, 8, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 1, 1, 2, 8, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B1', 1, 2, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B2', 1, 3, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B3', 1, 4, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B4', 1, 5, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B5', 1, 6, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B6', 1, 7, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B7', 1, 8, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'B8', 1, 9, 0, 8, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C', 2, 0, 2, 8, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 2, 1, 2, 8, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C1', 2, 2, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C2', 2, 3, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C3', 2, 4, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C4', 2, 5, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C5', 2, 6, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C6', 2, 7, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C7', 2, 8, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'C8', 2, 9, 0, 8, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D', 3, 0, 2, 8, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 3, 1, 2, 8, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D1', 3, 2, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D2', 3, 3, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D3', 3, 4, 0, 8, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D4', 3, 5, 0, 8, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D5', 3, 6, 0, 8, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D6', 3, 7, 0, 8, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D7', 3, 8, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'D8', 3, 9, 0, 8, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E', 4, 0, 2, 8, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 4, 1, 2, 8, NULL, 9)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E1', 4, 2, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E2', 4, 3, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E3', 4, 4, 0, 8, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E4', 4, 5, 0, 8, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E5', 4, 6, 0, 8, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E6', 4, 7, 0, 8, NULL, 2)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E7', 4, 8, 0, 8, NULL, 1)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'E8', 4, 9, 0, 8, NULL, 1)
                
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F', 5, 0, 2, 8, NULL, 7)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 1, 2, 8, NULL, 8)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 2, 2, 8, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 3, 2, 8, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F3', 5, 4, 0, 8, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F4', 5, 5, 0, 8, 355, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F5', 5, 6, 0, 8, NULL, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'F6', 5, 7, 0, 8, 357, 3)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 8, 2, 8, NULL, 10)
                INSERT INTO [dbo].[Seats] ([Code], [RowIndex], [ColIndex], [Status], [RoomId], [CoupleSeatId], [SeatTypeId]) VALUES (N'', 5, 9, 2, 8, NULL, 10)");

            migrationBuilder.Sql(@"
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'2D Phụ đề Việt', 0, 1)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'2D Phụ đề Anh', 0, 1)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'2D Lồng tiếng', 0, 1)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'3D Phụ đề Việt', 10000, 1)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'3D Phụ đề Anh', 10000, 1)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'3D Lồng tiếng', 10000, 1)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'2D Phụ đề Việt', 0, 2)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'2D Phụ đề Anh', 0, 2)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'2D Lồng tiếng', 0, 2)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'3D Phụ đề Việt', 5000, 1)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'3D Phụ đề Anh', 5000, 1)
                INSERT INTO [dbo].[ScreenFormats] ([Name], [ExtraFee], [CinemaChainId]) VALUES (N'3D Lồng tiếng', 5000, 1)");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
